### ISSUE TITLE
Unable to resolve Error 413 - Request Entity Too Large when POSTing file to the server

### ISSUE THREAD

**Issue by logreg-n-coffee** [selikapro/microservices-python#28]
Hi there,

I encountered an error when I was trying to post a random video file to the server. However, every time I was trying to POST the file using cURL, I got the following response. I tried modifying the ingress.yaml file but it did not work out. Just wondering if you have any ideas on how to solve the issue. Thank you.

Code tried in Terminal:

```bash
curl -X POST -F 'file=@./test.mp4' -H 'Authorization: Bearer TOKEN' http://mp3converter.com/upload
```

Response from server
```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by logreg-n-coffee** [comment]
I solved the above issue by adjusting the parameter in the ingress yaml file - ``gateway/manifests/ingress.yaml``.

## How I found the root of the issue
I noticed Error 413 was caused by uploading a large file and the server rejected the large files. After checking the pods, I noticed that all of the four pods ``auth converter gateway rabbitmq`` did not have anything logged down so I displayed all pods and found the issue was in the ``ingress-ngnix`` pod.

After I viewed the log generated by ``ingress-ngnix``, I saw error 413. Later, I examined the setting file by going into the ``ingress-ngnix``pod by entering its terminal, ``nano nginx.conf`` and examined the ``client_max_body_size`` setting, where ``client_max_body_size`` is ``1m``, which means that the ``gateway/manifests/ingress.yaml`` file did not apply correctly. 

## How I solved the issue
I modified the ``gateway/manifests/ingress.yaml`` file, and it is shown below:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m  # do not use a string quote in the proxy-body-size
spec:
  rules:
    - host: mp3converter.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080

```

## Useful documentation that helps
[https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size](url)

### Custom max body size

For NGINX, an 413 error will be returned to the client when the size in a request exceeds the maximum allowed size of the client request body. This size can be configured by the parameter [`client_max_body_size`](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size).

To configure this setting globally for all Ingress rules, the `proxy-body-size` value may be set in the [NGINX ConfigMap](./configmap.md#proxy-body-size).
To use custom values in an Ingress rule define these annotation:

```yaml
nginx.ingress.kubernetes.io/proxy-body-size: 8m
```
